import type { BlogPost } from "../blog";

const post: BlogPost = {
    id: "16",
    slug: "swagger-unit-testing-bearer-token-csharp-dotnet",
    title: "How to Set Up Swagger with JWT Bearer Tokens and Unit Tests in .NET",
    excerpt: "Swagger works out of the box until you add JWT authentication — then every request returns 401 and the test suite can't run. Here is the full setup that handles both correctly.",
    date: "2026-03-25",
    readTime: "8 min read",
    tags: [".NET", "C#", "ASP.NET Core", "Swagger", "Unit Testing", "JWT", "Backend"],
    content: `
<h2>Why Most .NET Backends Are Harder to Maintain Than They Should Be</h2>
<p>A well-set-up ASP.NET Core project has three things that most quickly-built backends are missing: Swagger configured with Bearer token support so you can actually test protected endpoints, services injected via interfaces so unit tests can mock them, and <code>[Authorize]</code> attributes applied at the controller level rather than only in the frontend.</p>
<p>Each of these is straightforward once you know the pattern. Together they give you a backend that is documented, testable, and secure — and that stays that way as the project grows.</p>

<h2>Setting Up Swagger With Bearer Token Authorization</h2>
<p>The default Swagger setup that gets generated by the ASP.NET Core template gives you endpoint documentation. It does not give you a way to test endpoints that require a JWT. The moment you add <code>[Authorize]</code> to a controller, every call from Swagger UI returns 401 — making the tool almost useless for your most important endpoints.</p>
<p>The fix is to configure Swagger to include a security definition for Bearer tokens. Add this to <code>Program.cs</code>:</p>

<pre><code>builder.Services.AddSwaggerGen(options =>
{
    options.SwaggerDoc("v1", new OpenApiInfo
    {
        Title = "My API",
        Version = "v1",
        Description = "ASP.NET Core Web API"
    });

    // Define the Bearer auth scheme
    options.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
    {
        Name         = "Authorization",
        Type         = SecuritySchemeType.Http,
        Scheme       = "Bearer",
        BearerFormat = "JWT",
        In           = ParameterLocation.Header,
        Description  = "Enter your JWT access token. Example: Bearer {token}"
    });

    // Require Bearer on all endpoints by default
    options.AddSecurityRequirement(new OpenApiSecurityRequirement
    {
        {
            new OpenApiSecurityScheme
            {
                Reference = new OpenApiReference
                {
                    Type = ReferenceType.SecurityScheme,
                    Id   = "Bearer"
                }
            },
            Array.Empty&lt;string&gt;()
        }
    });
});</code></pre>

<p>With this in place, the Swagger UI shows an "Authorize" button at the top. You paste your JWT (obtained from your login endpoint), click Authorize, and every subsequent call from the UI sends the token in the <code>Authorization</code> header — exactly as a real client would.</p>
<p>This means you can test your entire API — including protected routes — from the browser with no Postman setup required. For development speed and onboarding new developers, this is significant.</p>

<p>Also make sure the middleware pipeline in <code>Program.cs</code> has Swagger in the right order:</p>

<pre><code>if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI(c => c.SwaggerEndpoint("/swagger/v1/swagger.json", "My API v1"));
}

app.UseAuthentication(); // must come before UseAuthorization
app.UseAuthorization();

app.MapControllers();</code></pre>

<p><code>UseAuthentication</code> must come before <code>UseAuthorization</code> — this is a common mistake that causes 401 responses even when the token is valid.</p>

<h2>Interface-Driven Services — The Foundation of Testable Code</h2>
<p>A controller that directly instantiates a concrete service class cannot be unit tested without spinning up a real database, real HTTP clients, or real external dependencies. The solution is to inject services via interfaces, so tests can substitute a mock implementation.</p>
<p>Here is the pattern:</p>

<pre><code>// 1. Define the interface
public interface IUserService
{
    Task&lt;User?&gt;            GetByIdAsync(Guid id);
    Task&lt;IEnumerable&lt;User&gt;&gt; GetAllAsync();
    Task&lt;User&gt;             CreateAsync(CreateUserRequest request);
    Task                   DeleteAsync(Guid id);
}

// 2. Implement it
public class UserService : IUserService
{
    private readonly AppDbContext _db;
    public UserService(AppDbContext db) => _db = db;

    public async Task&lt;User?&gt; GetByIdAsync(Guid id)
        => await _db.Users.FindAsync(id);

    // ... other implementations
}

// 3. Register in Program.cs
builder.Services.AddScoped&lt;IUserService, UserService&gt;();</code></pre>

<p>The controller receives the interface, not the concrete type:</p>

<pre><code>[ApiController]
[Route("api/[controller]")]
[Authorize]
public class UsersController : ControllerBase
{
    private readonly IUserService _userService;

    public UsersController(IUserService userService)
    {
        _userService = userService;
    }

    [HttpGet("{id:guid}")]
    public async Task&lt;IActionResult&gt; GetUser(Guid id)
    {
        var user = await _userService.GetByIdAsync(id);
        return user is null ? NotFound() : Ok(user);
    }

    [HttpPost]
    public async Task&lt;IActionResult&gt; CreateUser(CreateUserRequest request)
    {
        var user = await _userService.CreateAsync(request);
        return CreatedAtAction(nameof(GetUser), new { id = user.Id }, user);
    }
}</code></pre>

<h2>Writing Unit Tests Against the Interface</h2>
<p>With the interface in place, your xUnit tests can mock the service entirely — no database, no real HTTP calls, no external dependencies:</p>

<pre><code>public class UsersControllerTests
{
    private readonly Mock&lt;IUserService&gt; _mockService;
    private readonly UsersController    _controller;

    public UsersControllerTests()
    {
        _mockService = new Mock&lt;IUserService&gt;();
        _controller  = new UsersController(_mockService.Object);
    }

    [Fact]
    public async Task GetUser_ReturnsOk_WhenUserExists()
    {
        // Arrange
        var userId = Guid.NewGuid();
        var fakeUser = new User { Id = userId, Email = "test@example.com" };

        _mockService
            .Setup(s =&gt; s.GetByIdAsync(userId))
            .ReturnsAsync(fakeUser);

        // Act
        var result = await _controller.GetUser(userId);

        // Assert
        var okResult = Assert.IsType&lt;OkObjectResult&gt;(result);
        var returned = Assert.IsType&lt;User&gt;(okResult.Value);
        Assert.Equal(userId, returned.Id);
    }

    [Fact]
    public async Task GetUser_ReturnsNotFound_WhenUserDoesNotExist()
    {
        // Arrange
        var userId = Guid.NewGuid();
        _mockService
            .Setup(s =&gt; s.GetByIdAsync(userId))
            .ReturnsAsync((User?)null);

        // Act
        var result = await _controller.GetUser(userId);

        // Assert
        Assert.IsType&lt;NotFoundResult&gt;(result);
    }

    [Fact]
    public async Task CreateUser_ReturnsCreatedAtAction()
    {
        // Arrange
        var request  = new CreateUserRequest { Email = "new@example.com" };
        var newUser  = new User { Id = Guid.NewGuid(), Email = request.Email };

        _mockService
            .Setup(s =&gt; s.CreateAsync(request))
            .ReturnsAsync(newUser);

        // Act
        var result = await _controller.CreateUser(request);

        // Assert
        var created = Assert.IsType&lt;CreatedAtActionResult&gt;(result);
        Assert.Equal(nameof(_controller.GetUser), created.ActionName);
    }
}</code></pre>

<p>These tests run in milliseconds and can run in CI with no infrastructure. They test the controller logic — routing, response codes, response shape — without touching the service implementation. Your service implementation gets its own set of integration tests that do hit a database.</p>

<h2>Bearer Token and the [Authorize] Attribute</h2>
<p>Swagger with Bearer support is only useful if your endpoints are actually protected. Hiding a route in the frontend is not authorization — any developer with a REST client can bypass the UI entirely.</p>
<p>Every endpoint that accesses user data or performs sensitive operations needs the <code>[Authorize]</code> attribute at the controller or action level:</p>

<pre><code>// Protect the whole controller — every action requires a valid token
[ApiController]
[Route("api/[controller]")]
[Authorize]
public class UsersController : ControllerBase
{
    // This action inherits [Authorize] from the controller
    [HttpGet("{id:guid}")]
    public async Task&lt;IActionResult&gt; GetUser(Guid id) { ... }

    // Admin-only endpoint — role enforced at the API layer, not the UI
    [Authorize(Roles = "Admin")]
    [HttpDelete("{id:guid}")]
    public async Task&lt;IActionResult&gt; DeleteUser(Guid id)
    {
        await _userService.DeleteAsync(id);
        return NoContent();
    }

    // Public endpoint — explicitly opt out of auth
    [AllowAnonymous]
    [HttpGet("public-profile/{id:guid}")]
    public async Task&lt;IActionResult&gt; GetPublicProfile(Guid id) { ... }
}</code></pre>

<p>For more granular rules, use policy-based authorization defined in <code>Program.cs</code>:</p>

<pre><code>builder.Services.AddAuthorization(options =>
{
    options.AddPolicy("SeniorDeveloperOnly", policy =>
        policy.RequireRole("Developer")
              .RequireClaim("seniority", "senior", "lead", "principal"));
});

// On the controller action
[Authorize(Policy = "SeniorDeveloperOnly")]
[HttpPost("deployments")]
public async Task&lt;IActionResult&gt; TriggerDeployment(DeploymentRequest request) { ... }</code></pre>

<h2>The Complete Program.cs Setup</h2>
<p>Here is a complete <code>Program.cs</code> that wires everything together — JWT authentication, Swagger with Bearer support, and interface registrations:</p>

<pre><code>using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.IdentityModel.Tokens;
using Microsoft.OpenApi.Models;
using System.Text;

var builder = WebApplication.CreateBuilder(args);

// Controllers
builder.Services.AddControllers();

// Swagger with Bearer token support
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(options =>
{
    options.SwaggerDoc("v1", new OpenApiInfo { Title = "My API", Version = "v1" });

    options.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
    {
        Name         = "Authorization",
        Type         = SecuritySchemeType.Http,
        Scheme       = "Bearer",
        BearerFormat = "JWT",
        In           = ParameterLocation.Header,
        Description  = "Enter: Bearer {your JWT token}"
    });

    options.AddSecurityRequirement(new OpenApiSecurityRequirement
    {
        {
            new OpenApiSecurityScheme
            {
                Reference = new OpenApiReference
                {
                    Type = ReferenceType.SecurityScheme,
                    Id   = "Bearer"
                }
            },
            Array.Empty&lt;string&gt;()
        }
    });
});

// JWT Authentication
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(options =>
    {
        options.TokenValidationParameters = new TokenValidationParameters
        {
            ValidateIssuerSigningKey = true,
            IssuerSigningKey = new SymmetricSecurityKey(
                Encoding.UTF8.GetBytes(builder.Configuration["Jwt:SecretKey"]!)
            ),
            ValidateIssuer   = true,
            ValidIssuer      = builder.Configuration["Jwt:Issuer"],
            ValidateAudience = true,
            ValidAudience    = builder.Configuration["Jwt:Audience"],
            ValidateLifetime = true,
            ClockSkew        = TimeSpan.Zero
        };
    });

builder.Services.AddAuthorization();

// Service registrations via interfaces
builder.Services.AddScoped&lt;IUserService, UserService&gt;();
builder.Services.AddScoped&lt;ITokenService, TokenService&gt;();

var app = builder.Build();

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();
app.UseAuthentication();  // Order matters — auth before authz
app.UseAuthorization();
app.MapControllers();

app.Run();</code></pre>

<h2>Why This Setup Pays Off</h2>
<p>This pattern — Swagger with Bearer support, interface injection, and <code>[Authorize]</code> at the controller level — is not gold-plating. It directly solves real problems:</p>
<ul>
  <li><strong>Development speed:</strong> You can test every endpoint, including protected ones, directly from the Swagger UI without configuring Postman or writing curl scripts.</li>
  <li><strong>Confidence:</strong> Unit tests with mocked interfaces run in milliseconds in CI. You know controller logic is correct before the code ships.</li>
  <li><strong>Security:</strong> Authorization at the API layer means the backend is protected regardless of what the frontend does or does not do.</li>
  <li><strong>Maintainability:</strong> When requirements change, you update the interface and its implementation. Everything that depends on the interface — including tests — still compiles cleanly.</li>
</ul>
<p>I apply this setup on every .NET backend project I take on. If you are starting a new ASP.NET Core API or inheriting one that does not have this structure yet, these are the three things worth setting up first.</p>
<p>If you are setting up a new ASP.NET Core project, see the full list of <a href="/services/dotnet-backend">.NET backend development services</a> I offer, or <a href="/contact">get in touch</a> directly.</p>
    `.trim(),
};

export default post;
